In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array(([3,5],[5,1],[10,2]), dtype=float)
y = np.array(([75,], [82], [93]), dtype=float)

In [4]:
# Normalize the data
X = X/np.amax(X, axis=0)
y = y/100 #Max test score is 100

In [5]:
def sigmoid(z):
    #Apply sigmoid activation function
    return 1/(1+np.exp(-z))

In [6]:
testInput = np.arange(-6,6,0.01)
plt.plot(testInput, sigmoid(testInput), linewidth=2)
plt.grid(1)
plt.show()

In [7]:
sigmoid(1)

0.7310585786300049

In [8]:
sigmoid(np.array([-1,0,1]))

array([ 0.26894142,  0.5       ,  0.73105858])

In [9]:
sigmoid(np.random.randn(3,3))

array([[ 0.28363364,  0.63920799,  0.61652918],
       [ 0.1962755 ,  0.73739128,  0.77545653],
       [ 0.2757373 ,  0.20628147,  0.31643873]])

In [10]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def forward(self, X):
        #Propagate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))

In [11]:
NN = Neural_Network()

In [12]:
yHat = NN.forward(X)

In [13]:
yHat

array([[ 0.73338893],
       [ 0.71578576],
       [ 0.76704787]])

In [14]:
y

array([[ 0.75],
       [ 0.82],
       [ 0.93]])

In [15]:
NN.W1[0,0] = 1.1
yHat = NN.forward(X)

In [16]:
sum(0.5*(y-yHat)**2)

array([ 0.03228124])

In [17]:
def sigmoidPrime(z):
    #Derivative of Sigmoid Function
    return np.exp(-z)/((1+np.exp(-z))**2)

In [ ]:
testValues = np.arange(-5,5,0.01)
plt.plot(testValues, sigmoid(testValues), linewidth=2)
plt.plot(testValues, sigmoidPrime(testValues), linewidth=2)
plt.grid(1)
plt.legend(['sigmoid', 'sigmoidPrime'])
plt.show()