In [29]:
import numpy as np
import matplotlib.pyplot as plt

In [30]:
X = np.array(([3,5],[5,1],[10,2]), dtype=float)
y = np.array(([75,], [82], [93]), dtype=float)

In [31]:
print X

[[  3.   5.]
 [  5.   1.]
 [ 10.   2.]]


In [32]:
print y

[[ 75.]
 [ 82.]
 [ 93.]]


In [33]:
# Normalize the data
X = X/np.amax(X, axis=0)
y = y/100 #Max test score is 100

In [34]:
print X

[[ 0.3  1. ]
 [ 0.5  0.2]
 [ 1.   0.4]]


In [35]:
print y

[[ 0.75]
 [ 0.82]
 [ 0.93]]


In [44]:
print X.shape, y.shape

(3, 2) (3, 1)


In [45]:
def sigmoid(z):
    #Apply sigmoid activation function to scalar, vector, or matrix
    return 1/(1+np.exp(-z))

In [48]:
sigmoid(1)

0.7310585786300049

In [50]:
sigmoid(np.array([-1,0,1]))

array([ 0.26894142,  0.5       ,  0.73105858])

In [51]:
sigmoid(np.random.randn(3,3))

array([[ 0.07110389,  0.66795473,  0.36660051],
       [ 0.29484552,  0.64929371,  0.71522278],
       [ 0.49211893,  0.38943082,  0.26187555]])

In [ ]:
testInput = np.arange(6,6,0.01)
plt.plot(testInput, sigmoid(testInput), linewidth=2)
plt.grid(1)
plt.show()
