In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array(([3,5],[5,1],[10,2]), dtype=float)
y = np.array(([75,], [82], [93]), dtype=float)

In [3]:
# Normalize the data
X = X/np.amax(X, axis=0)
y = y/100 #Max test score is 100

In [4]:
def sigmoid(z):
    #Apply sigmoid activation function
    return 1/(1+np.exp(-z))

In [13]:
testInput = np.arange(-6,6,0.01)
plt.plot(testInput, sigmoid(testInput), linewidth=2)
plt.grid(1)
plt.show()

In [14]:
sigmoid(1)

0.7310585786300049

In [16]:
sigmoid(np.array([-1,0,1]))

array([ 0.26894142,  0.5       ,  0.73105858])

In [18]:
sigmoid(np.random.randn(3,3))

array([[ 0.10311386,  0.86570302,  0.12607628],
       [ 0.61229688,  0.68946432,  0.57437302],
       [ 0.63624531,  0.70325793,  0.29903809]])

In [22]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def forward(self, X):
        #Propagate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))

In [23]:
NN = Neural_Network()

In [24]:
yHat = NN.forward(X)

In [25]:
yHat

array([[ 0.32317929],
       [ 0.32696157],
       [ 0.3542547 ]])

In [26]:
y

array([[ 0.75],
       [ 0.82],
       [ 0.93]])