In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
X = np.array(([3,5],[5,1],[10,2]), dtype=float)
y = np.array(([75,], [82], [93]), dtype=float)

In [25]:
# Normalize the data
X = X/np.amax(X, axis=0)
y = y/100 #Max test score is 100

In [26]:
def sigmoid(z):
    #Apply sigmoid activation function
    return 1/(1+np.exp(-z))

In [27]:
testInput = np.arange(-6,6,0.01)
plt.plot(testInput, sigmoid(testInput), linewidth=2)
plt.grid(1)
plt.show()

In [29]:
sigmoid(1)

0.7310585786300049

In [30]:
sigmoid(np.array([-1,0,1]))

array([ 0.26894142,  0.5       ,  0.73105858])

In [31]:
sigmoid(np.random.randn(3,3))

array([[ 0.7534386 ,  0.83375788,  0.20789515],
       [ 0.24138316,  0.55519854,  0.68573797],
       [ 0.46980381,  0.65457844,  0.69964851]])

In [32]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def forward(self, X):
        #Propagate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))

In [33]:
NN = Neural_Network()

In [34]:
yHat = NN.forward(X)

In [35]:
yHat

array([[ 0.55559185],
       [ 0.58853724],
       [ 0.55657346]])

In [36]:
y

array([[ 0.75],
       [ 0.82],
       [ 0.93]])

In [37]:
NN.W1[0,0] = 1.1
yHat = NN.forward(X)

In [38]:
sum(0.5*(y-yHat)**2)

array([ 0.03754425])

In [39]:
def sigmoidPrime(z):
    #Derivative of Sigmoid Function
    return np.exp(-z)/((1+np.exp(-z))**2)

In [40]:
testValues = np.arange(-5,5,0.01)
plt.plot(testValues, sigmoid(testValues), linewidth=2)
plt.plot(testValues, sigmoidPrime(testValues), linewidth=2)
plt.grid(1)
plt.legend(['sigmoid', 'sigmoidPrime'])
plt.show()

In [42]:
def costFunctionPrime(self, X, y):
    #Compute derivative with respect W1 and W2
    self.yHat = self.forward(X)
    
    delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
    dJdW2 = np.dot(self.a2.T, delta3)
    
    delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
    dJdW1 = np.dot(X.T, delta2)
    
    return djdW1, dJdW2